### ISSUE TITLE
Align to top instead center

### ISSUE THREAD

**Issue by scudlava** [GitHubZJY/AndroidPdfHelper#4]
Hi, thank you for great library before

Can we use content into align top instead center ? 

Thanks

**Comment by scudlava** [comment]
I see in your class **PdfPageAdapter** on method **onViewAttachedToWindow**

 i see configuration for ScaleType into fit_center and i change into FIT_START solve my issues

**Comment by GitHubZJY** [comment]
yep, you can set the scale type you want with onBindViewHolder in adapter
